# Generated by Django 4.2.4 on 2023-08-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta1', models.CharField(max_length=255)),
                ('resposta2', models.CharField(max_length=255)),
                ('resposta3', models.CharField(max_length=255)),
                ('resposta4', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pessoas',
            name='respostas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_respostas', to='pessoas.respostas'),
        ),
    ]
