# Generated by Django 4.2.4 on 2023-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_valores_remove_pessoas_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
