# Generated by Django 4.2.4 on 2023-09-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_valores_valorcorrida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valores',
            name='pessoa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valores',
            name='valorCorrida',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valorCorridaComDesconto',
            field=models.CharField(max_length=10),
        ),
    ]
