# Generated by Django 4.2.2 on 2023-09-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxistas',
            new_name='Taxista',
        ),
    ]
